<a href="https://colab.research.google.com/github/waraporn19/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# เกี่ยวกับตัวเลข
import numpy as np

#Numpy Array

In [8]:
np1 = np.array([[1,3,5],[2,4,6]]) # สร้าง numpy array แถวที่ 1-2 
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]]) # สร้าง numpy array แถวที่ 1-4 
np2


array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [10]:
np2.T # Transpost

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [11]:
np2[0,:] # ดูข้อมูล แถวแรก(0) ข้อมูลทุกตัว(:)ในแถวแรก

array([1, 2])

#HW 6

สร้าง Distance matrix (Manhattan and Euclidean) ของ np2 โดยสร้าง function สำหรับคำนวณ Manhattan distance และ Euclidean distance

''' def Euclidean(data1,data2);

#process return dist

'''

In [34]:
import math

In [35]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0]) # ใส่ abs เพื่อให้มันเป็นบวก
    distY = abs(data1[1]-data2[1]) # Y อยู่ตำแหน่งที่ 1
    return distX+distY

In [36]:
Manhattan(np2[0,:],np2[1,:])

5

In [37]:
# สร้าง array เปล่า 4x4 มาจากจำนวนข้อมูล .zeros คือเริ่มจาก 0 .zone ก็มี
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
for i in range(4):
    for j in range(4):
      dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
      
dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [39]:
np2.shape # บอกจำนวนแถวและหลัก ของ เมตริกซ์

(4, 2)

In [40]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [41]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])