<a href="https://colab.research.google.com/github/waraporn19/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# เกี่ยวกับตัวเลข
import numpy as np

#Numpy Array

In [ ]:
np1 = np.array([[1,3,5],[2,4,6]]) # สร้าง numpy array แถวที่ 1-2 
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]]) # สร้าง numpy array แถวที่ 1-4 
np2


array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
np2.T # Transpost

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [ ]:
np2[0,:] # ดูข้อมูล แถวแรก(0) ข้อมูลทุกตัว(:)ในแถวแรก

array([1, 2])

#HW 6

สร้าง Distance matrix (Manhattan and Euclidean) ของ np2 โดยสร้าง function สำหรับคำนวณ Manhattan distance และ Euclidean distance

''' def Euclidean(data1,data2);

#process return dist

'''

In [ ]:
import math

In [ ]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0]) # ใส่ abs เพื่อให้มันเป็นบวก
    distY = abs(data1[1]-data2[1]) # Y อยู่ตำแหน่งที่ 1
    return distX+distY

In [ ]:
Manhattan(np2[0,:],np2[1,:])

5

In [ ]:
# สร้าง array เปล่า 4x4 มาจากจำนวนข้อมูล .zeros คือเริ่มจาก 0 .zone ก็มี
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
    for j in range(4):
      dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
      
dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [ ]:
np2.shape # บอกจำนวนแถวและหลัก ของ เมตริกซ์

(4, 2)

In [ ]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [ ]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

#Distance of nominal or categorical features
(extra) python data structure (Dictionary)


In [ ]:
d_A={'a':1,2:3,3:5,'cat':6}#ใส่ค่า 1 คืนค่า 3 คือ คำสั่งสร้างDictionary

In [ ]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [ ]:
d_A['cat']

6

In [ ]:

d_A['dag'] = [1,2,3,4,5] #เพิ่มค่าเข้าไปใน dict

In [ ]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dag': [1, 2, 3, 4, 5]}

In [ ]:
del d_A['dag'] #ลบค่าใน Dict

In [ ]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [ ]:
d_A['dog'] = [1,2,3,4,5]

In [ ]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [ ]:
import pandas as pd

In [ ]:
data_dict = {'color':['red','red','green'], #มีค่าที่เป็นไปได้ color = 'rad', 'green', 'blue'
             'status':['single','married','single']} #status = 'single','married','single'
data_dict            

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [ ]:
data_pd = pd.DataFrame.from_dict(data_dict)#สร้างตาราง ใช้คำสั่งfrom_dict
data_pd

color   status
0    red   single
1    red  married
2  green   single

#Categorical feature distance method#1

In [ ]:
list(data_pd.iloc[0,:])

['red', 'single']

In [ ]:
def meth1_dist(data1,data2):
    N = 0     #จำนวนของ unmath ตัวที่ไม่ตรงกัน
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feature{i} of data1 is {data1[1]} , feature{i} of data1 is {data2[1]} ')
        if data1[i] != data2[i]: 
          N = N+1
          print(f'  {data1[i]} is not equal {data2[i]} : update ({N})')
        else:
           print(f'  {data1[i]} is equal {data2[i]}')
    return N/len(data1)

In [ ]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']
feature0 of data1 is single , feature0 of data1 is married 
  red is equal red
feature1 of data1 is single , feature1 of data1 is married 
  single is not equal married : update (1)


0.5

#HW7 calculate distance matrix of data_pd using math1_dist()





#Categorical features distance method#2

In [ ]:
pd.get_dummies(data_pd)

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [ ]:
data_pd_binary = pd.get_dummies(data_pd) # เพิ่มตัวแปรมารับค่าตาราง

In [ ]:
#คำนวณ binary 
def binary_sym_dist(data1,data2): #สร้างฟังก์ชัน
    q = 0 #จำนวน ที่เป็น 1 เหมือนกัน
    rs = 0 #ค่าไม่เท่ากัน 01
    t = 0 #จำนวนที่เป็น 0 เหมือนกัน
    for i in range(len(data1)):
      if data1[i] == data2[i]: 
          if data1[i] == 1:
            q = q + 1
          else:
            t = t + 1
      if data1[i] != data2[i]:
          rs = rs + 1
    return (rs)/(q+rs+t)

In [ ]:
binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

0.5

#HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

Numpy Array, process, Distance of nominal or categorical features

สร้าง array ที่มีค่าเป็น 1 ด้วย np.ones([ขนาดแถว, ขนาดหลัก]) : (( , ))

สร้าง array ที่มีค่าเป็น 0 ด้วย np.zeros([ขนาดแถว, ขนาดหลัก])